"""
The ``zen.generating`` package contains functions for generating various standard graphs and networks.  
As in other modules, calling and return conventions have been standardized wherever possible.

In this package, a network is generated by a single call to a generation function.  Generation functions have specialized parameters
which will be the first positional arguments.  Optional keyword arguments may include:

	* ``seed [=-1]`` (int): set the seed for a random generator being used to generate the network.  Note that deterministic generation
	  algorithms will not support (or need) this argument.  The default value causes no internal seed to be set, producing the
	  effect of causing the generator to use whatever the current seed is.
"""

from rgm import *